services:
  dev:
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
      args:
        USER_NAME: user
        USER_PASSWORD: pass
        USER_UID: 1000
        USER_GID: 1000
    user: 1000:1000
    ports:
      - 22222:22
    volumes:
      - ssh_host_keys:/etc/ssh/ssh_host_keys
      - home:/home
      - .:/workspace
    working_dir: /workspace
    tty: true

volumes:
  ssh_host_keys:
  home: