services:
  dev:
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
      args:
        USER_NAME: user
        USER_PASSWORD: pass
        USER_UID: 1000
        USER_GID: 1000
    user: 1000:1000
    ports:
      - 22222:22
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true