services:
  dev:
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    user: ${USER_UID}:${USER_GID}
    ports:
      - ${SSH_PORT}:22
    volumes:
      - ssh_host_keys:/etc/ssh/ssh_host_keys
      - home:/home
      - .:/workspace
    working_dir: /workspace
    tty: true

volumes:
  ssh_host_keys:
  home: